
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'cl-primary': '#f4f6f0',
        'cl-secondary': '#f4f6f0',
        'cl-tertiary': '#f6f2f0',
        'black-dark': '#202020',
        'black-darkest': '#151515',
        'black-gray': '#333333',
        'grey-normal': '#565656',
        'grey-dark': '#18191f',
        'grey-lightest': '#e4e4e4',
        'grey-light': '#f6f5f0',
        'grey-light2': '#f0f1f6',
        'grey-light3': '#e3e0d0',
        'grey-blue': '#00a6fb',
        'grey-bluish': '#1c2c40',
        'codelabs-primary1': '#8b00ff',
        'codelabs-primary2': '#ae4dff',
        'codelabs-primary3': '#c680ff',
        'codelabs-primary4': '#ddb3ff',
        'codelabs-primary5': '#f4e6ff',
        'codelabs-secondary1': '#f6ff81',
        'codelabs-secondary2': '#f9ffa7',
        'codelabs-secondary3': '#fbffc0',
        'codelabs-secondary4': '#fdffda',
        'codelabs-secondary5': '#fffff3',
        'codelabs-tertiary1': '#fe9dc5',
        'codelabs-tertiary2': '#ffbbd7',
        'codelabs-tertiary3': '#ffcee2',
        'codelabs-tertiary4': '#ffe2ee',
        'codelabs-tertiary5': '#fff6fa',
        'codelabs-quaternary1': '#fc9360',
        'codelabs-quaternary2': '#fdb490',
        'codelabs-quaternary3': '#fec9b0',
        'codelabs-quaternary4': '#ffdfd0',
        'codelabs-quaternary5': '#fff5f0',
        'codelabs-grey1': '#4c4b4c',
        'codelabs-grey2': '#828283',
        'codelabs-grey3': '#a6a6a6',
        'codelabs-grey4': '#cacaca',
        'codelabs-grey5': '#f0eef3',
        'codelabs-text-light-primary': '#262628',
        'codelabs-text-light-secondary': '#4c4b4c',
        'blue-lightest': '#f0faff',
      },
      fontFamily: {
        'montserrat': ['var(--font-montserrat)', 'sans-serif'],
        'poppins': ['var(--font-poppins)', 'sans-serif'],
      },
      height: {
        '256': '64rem',
        '272': '68rem',
        '485': '121.25rem',
        '490': '122.5rem',
        '500': '125rem',
        '550': '137.5rem',
        '596': '149rem',
        '702': '175.5rem',
      },
      width: {
        '200.25': '50.0625rem',
      },
      aspectRatio: {
        '2/3': '2 / 3',
        '5/2': '5 / 2',
      },
      maxWidth: {
        '392': '24.5rem',
        '540': '33.75rem',
        '600': '37.5rem',
        '8xl': '88rem',
      },
      mask: {
        '[radial-gradient(32rem_32rem_at_center,white,transparent)]': 'radial-gradient(32rem 32rem at center, white, transparent)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
